services:
  - type: web
    name: sanskrit-ai-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "flask run --host=0.0.0.0 --port=5000"
    envVars:
      - key: MONGO_URI
        fromDatabase:
          name: your-database-name
          property: connectionString
    plan: free
    region: oregon